language: go
go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - "1.10"
  - tip
install:
  - go get -v ./...
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin
script:
  - $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --failOnPending --randomizeSuites --race
