language: go
go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - "1.10"
  - tip
install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin
script:
  - ginkgo -r --randomizeAllSpecs --failOnPending --randomizeSuites --race
